.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.7

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  QT_QPA_PLATFORM: offscreen

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - apt update
  - apt install -y xvfb # Sets up a headless display
  - sleep 3

stages:
  - Static Analysis
  - Test
  - Deploy

test:
  stage: Test
  script:
    - apt install -y graphviz graphviz-dev
    - pip install -e .
    - pip install -r requirements_dev.txt
    - xvfb-run py.test -s --cov=autodepgraph --cov-report xml --cov-report html --cov-report term --cov-config=.coveragerc --color=yes
  artifacts:
    paths:
      - htmlcov
      - coverage.xml
    reports:
      cobertura: coverage.xml
    when: always

test-win-3.8:
  before_script:
    - choco install python --version=3.8.3 -y -f
    - "C:\\Python38\\python.exe -m pip install -U pip"
  extends:
    - .shared_windows_runners
    - test
  script:
    - "C:\\Python38\\python.exe -m pip install -e ."
    - "C:\\Python38\\python.exe -m pip install pytest pytest-runner pytest-cov scikit-learn==0.23.1 scikit-optimize"
    - "C:\\Python38\\Scripts\\py.test.exe -s --cov=quantify --cov-report xml --cov-report html --cov-report term --cov-config=.coveragerc --color=yes"
  only:
    - develop
  allow_failure: true

test-3.8:
  extends: "test"
  image: "python:3.8"

test-latest:
  extends: "test"
  image: "python:latest"
  allow_failure: true

flake8:
  image: python:3.8
  stage: Static Analysis
  allow_failure: true
  script:
    - pip install -r requirements_dev.txt
    - flake8 quantify --format=html --htmldir=flake-report
  artifacts:
    paths:
      - flake-report
    when: on_failure

run:
  stage: Test
  script:
    - apt install -y graphviz graphviz-dev
    - python setup.py bdist_wheel
    # an alternative approach is to install and run:
    - pip install dist/*
    # run the command here
  artifacts:
    paths:
      - dist/*.whl
