language: python
notifications:
  email: false

cache: pip

python:
  - "3.6"

env:
    - TRAVISCI=true
# command to install dependencies
install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install git+git://github.com/DiCarloLab-Delft/Qcodes.git
    - pip install coverage pytest-cov pytest --upgrade
    - pip install codacy-coverage
    - pip install -e .
before_script: # configure a headless display to test plot generation
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

# command to run tests
script:
    - py.test --cov=autodepgraph --cov-report xml --cov-config=.coveragerc

after_success:
    # install codacy coverage plugin and sphinx only on traivs
    - pip install codacy-coverage sphinx sphinx_rtd_theme jsonschema sphinxcontrib-jsonschema
    - python-codacy-coverage -r coverage.xml
    # build the docs
    # - make -f docs/Makefile gh-pages
